package mchorse.mappet.utils;

import mchorse.mclib.client.gui.utils.Icon;
import mchorse.mclib.client.gui.utils.IconRegistry;
import mchorse.mclib.utils.resources.ResourceLocation;

public class MPIcons {
   public static final ResourceLocation TEXTURE = new ResourceLocation("mappet", "textures/gui/icons.png");
   public static final ResourceLocation KEYICONS = new ResourceLocation("mappet", "textures/gui/keyicons.png");
   public static final ResourceLocation LVICONS = new ResourceLocation("mappet", "textures/gui/lvicons.png");
   public static final Icon REPL;
   public static final Icon IN;
   public static final Icon OUT;
   public static final Icon HTML;
   public static final Icon BULLET;
   public static final Icon PARTICLE;
   public static final Icon SCENE;
   public static final Icon REWIND;
   public static final Icon FACES;
   public static final Icon ALEX;
   public static final Icon SELECTOR;
   public static final Icon SLASH;
   public static final Icon TEXT;
   public static final Icon LIKE;
   public static final Icon DISLIKE;
   public static final Icon YOUTUBE;
   public static final Icon DISCORD;
   public static final Icon TELEGRAM;
   public static final Icon VK;
   public static final Icon TWITTER;
   public static final Icon SOLID_LIKE;
   public static final Icon SOLID_DISLIKE;
   public static final Icon HUB;
   public static final Icon GITHUB;
   public static final Icon OTHER_BRIEFCASE;
   public static final Icon OTHER_MEDKIT;
   public static final Icon OTHER_WALLET;
   public static final Icon OTHER_HANGER;
   public static final Icon OTHER_STATS;
   public static final Icon OTHER_BANNER;
   public static final Icon OTHER_OPENED_LOCK;
   public static final Icon OTHER_CLOSED_LOCK;
   public static final Icon OTHER_FLAG;
   public static final Icon OTHER_FINISHFLAG;
   public static final Icon OTHER_UMBRELLA;
   public static final Icon OTHER_STAR;
   public static final Icon OTHER_STAR_2;
   public static final Icon OTHER_DUNGEONKEY;
   public static final Icon OTHER_CARKEY;
   public static final Icon OTHER_KEY;
   public static final Icon OTHER_X;
   public static final Icon OTHER_BACKPACK;
   public static final Icon OTHER_GLOSARY;
   public static final Icon OTHER_BOOK;
   public static final Icon OTHER_DOCUMENT;
   public static final Icon OTHER_CANDLE;
   public static final Icon OTHER_HOOK;
   public static final Icon ADMINPANEL_USER;
   public static final Icon ADMINPANEL_USER_WHITE_CROSS;
   public static final Icon ADMINPANEL_USER_RED_CROSS;
   public static final Icon ADMINPANEL_MESSAGE;
   public static final Icon ADMINPANEL_MESSAGE_WHITE_CROSS;
   public static final Icon ADMINPANEL_MESSAGE_RED_CROSS;
   public static final Icon ADMINPANEL_VOICE;
   public static final Icon ADMINPANEL_VOICE_WHITE_CROSS;
   public static final Icon ADMINPANEL_VOICE_RED_CROSS;
   public static final Icon ADMINPANEL_SPEAKER;
   public static final Icon ADMINPANEL_SPEAKER_WHITE_CROSS;
   public static final Icon ADMINPANEL_SPEAKER_RED_CROSS;
   public static final Icon ADMINPANEL_SPEAKER_MUTED;
   public static final Icon ADMINPANEL_SPEAKER_LOW;
   public static final Icon ADMINPANEL_SPEAKER_HIGH;
   public static final Icon TOOLS_SWORD;
   public static final Icon TOOLS_KNIFE;
   public static final Icon TOOLS_DAGGER;
   public static final Icon TOOLS_SHORTSWORD;
   public static final Icon TOOLS_KATANA;
   public static final Icon TOOLS_HAMMER;
   public static final Icon TOOLS_SCREWDRIVER;
   public static final Icon TOOLS_SHOVEL;
   public static final Icon TOOLS_GLOVE;
   public static final Icon TOOLS_SHURIKEN;
   public static final Icon TOOLS_BOW;
   public static final Icon TOOLS_LONGBOW;
   public static final Icon TOOLS_ARROW;
   public static final Icon TOOLS_FLYINGARROWS;
   public static final Icon TOOLS_SHOT;
   public static final Icon TOOLS_BULLET;
   public static final Icon TOOLS_PISTOL;
   public static final Icon TOOLS_GLOCK;
   public static final Icon TOOLS_REVOLVER;
   public static final Icon TOOLS_UZI;
   public static final Icon TOOLS_DYNAMITE;
   public static final Icon TOOLS_GRENADE;
   public static final Icon TOOLS_TNT;
   public static final Icon CLOTHES_CROWN;
   public static final Icon CLOTHES_MINICROWN;
   public static final Icon CLOTHES_CYLINDER;
   public static final Icon CLOTHES_HAT;
   public static final Icon CLOTHES_CAP;
   public static final Icon CLOTHES_CHRISTMASHAT;
   public static final Icon CLOTHES_FAVOUR;
   public static final Icon CLOTHES_GLASSES;
   public static final Icon CLOTHES_TSHORT;
   public static final Icon CLOTHES_JACKET;
   public static final Icon CLOTHES_PANTS;
   public static final Icon CLOTHES_BOOTS;
   public static final Icon CLOTHES_SNEAKERS;
   public static final Icon CLOTHES_MOUSTACHE;
   public static final Icon DEVICE_LAPTOP;
   public static final Icon DEVICE_COMPUTER;
   public static final Icon DEVICE_COMPUTER_2;
   public static final Icon DEVICE_DISKDRIVE;
   public static final Icon DEVICE_PHONE;
   public static final Icon DEVICE_RADIO;
   public static final Icon DEVICE_CAMERA;
   public static final Icon DEVICE_ARCADE;
   public static final Icon DEVICE_ANTENNA;
   public static final Icon DEVICE_CLOCK;
   public static final Icon DEVICE_MOUSE;
   public static final Icon DEVICE_KEYBOARD;
   public static final Icon DEVICE_GAMEPAD;
   public static final Icon DEVICE_MICROPHONE;
   public static final Icon DEVICE_HEADPHONES;
   public static final Icon DEVICE_SPEAKER;
   public static final Icon COMPUTER_CURSOR;
   public static final Icon COMPUTER_CLICK;
   public static final Icon COMPUTER_SHUTDOWN;
   public static final Icon COMPUTER_SETTINGS;
   public static final Icon COMPUTER_USB;
   public static final Icon COMPUTER_BATTERY_4;
   public static final Icon COMPUTER_BATTERY_3;
   public static final Icon COMPUTER_BATTERY_2;
   public static final Icon COMPUTER_BATTERY_1;
   public static final Icon COMPUTER_CHARGING;
   public static final Icon COMPUTER_NOTIFICATION;
   public static final Icon COMPUTER_DEFENDER;
   public static final Icon COMPUTER_HOME;
   public static final Icon COMPUTER_MAIL;
   public static final Icon COMPUTER_MARKET;
   public static final Icon COMPUTER_LIGHT;
   public static final Icon COMPUTER_MAP;
   public static final Icon COMPUTER_MAPPOINT;
   public static final Icon COMPUTER_SHARE;
   public static final Icon COMPUTER_SHARE_2;
   public static final Icon COMPUTER_FOLDER;
   public static final Icon COMPUTER_FILE;
   public static final Icon COMPUTER_PASTE;
   public static final Icon COMPUTER_CREDITCARD;
   public static final Icon COMPUTER_PIANO;
   public static final Icon COMPUTER_CD;
   public static final Icon COMPUTER_CASSETE;
   public static final Icon COMPUTER_NOTE;
   public static final Icon COMPUTER_NOTE_2;
   public static final Icon PAINT_PENCIL;
   public static final Icon PAINT_PENCILERASER;
   public static final Icon PAINT_HIGHLITGHTER;
   public static final Icon PAINT_BRUSH;
   public static final Icon PAINT_BRUSH_2;
   public static final Icon PAINT_PICKER;
   public static final Icon PAINT_ERASER;
   public static final Icon PAINT_POURING;
   public static final Icon PAINT_CUT;
   public static final Icon FOOD_PAN;
   public static final Icon FOOD_SPOON;
   public static final Icon FOOD_MEAT;
   public static final Icon FOOD_PIZZA;
   public static final Icon FOOD_BREAD;
   public static final Icon FOOD_SOUP;
   public static final Icon FOOD_CAKE;
   public static final Icon FOOD_CHOCOLATE;
   public static final Icon FOOD_ICECREAM;
   public static final Icon FOOD_ICECREAM_2;
   public static final Icon FOOD_CHUPACHUPS;
   public static final Icon FOOD_LOLLIPOP;
   public static final Icon FOOD_CHRISTMASLOLLIPOP;
   public static final Icon FOOD_TEA;
   public static final Icon FOOD_COFFEE;
   public static final Icon FOOD_BEAR;
   public static final Icon FOOD_JAM;
   public static final Icon FOOD_CHAMPAGNE;
   public static final Icon FOOD_COCACOLA;
   public static final Icon FOOD_CUP;
   public static final Icon FOOD_GLASS;
   public static final Icon FOOD_VIAL;
   public static final Icon FOOD_POTION;
   public static final Icon FOOD_CIGARETTE;
   public static final Icon FOOD_PIPE;
   public static final Icon FOOD_LIGHTER;
   public static final Icon FOOD_HOOKAH;
   public static final Icon FOOD_POOP;
   public static final Icon EMOJI_SMILEY;
   public static final Icon EMOJI_RELAXED;
   public static final Icon EMOJI_STUCKOUTTONGUE;
   public static final Icon EMOJI_SMIRKING;
   public static final Icon EMOJI_COOL;
   public static final Icon EMOJI_SOB;
   public static final Icon EMOJI_VERYSOB;
   public static final Icon EMOJI_CONFUSED;
   public static final Icon EMOJI_RAGE;
   public static final Icon EMOJI_SKULL_LARGE;
   public static final Icon EMOJI_SKULL_MEDIUM;
   public static final Icon EMOJI_SKULL_SMALL;
   public static final Icon MONEY_COIN;
   public static final Icon MONEY_COINDOLLAR;
   public static final Icon MONEY_BANKNOTES;
   public static final Icon MONEY_BAGMONEY;
   public static final Icon KEY_ESCAPE;
   public static final Icon KEY_F1;
   public static final Icon KEY_F2;
   public static final Icon KEY_F3;
   public static final Icon KEY_F4;
   public static final Icon KEY_F5;
   public static final Icon KEY_F6;
   public static final Icon KEY_F7;
   public static final Icon KEY_F8;
   public static final Icon KEY_F9;
   public static final Icon KEY_F10;
   public static final Icon KEY_F11;
   public static final Icon KEY_F12;
   public static final Icon KEY_PRINT;
   public static final Icon KEY_GRAVIAS;
   public static final Icon KEY_TILDA;
   public static final Icon KEY_EXCLAMATION;
   public static final Icon KEY_SYMBOL;
   public static final Icon KEY_GRID;
   public static final Icon KEY_DOLLAR;
   public static final Icon KEY_PROCENT;
   public static final Icon KEY_CARET;
   public static final Icon KEY_AMPERSAND;
   public static final Icon KEY_STAR;
   public static final Icon KEY_LEFT_PARENTTHESIS;
   public static final Icon KEY_RIGHT_PARENTTHESIS;
   public static final Icon KEY_INSERT;
   public static final Icon KEY_HOME;
   public static final Icon KEY_1;
   public static final Icon KEY_2;
   public static final Icon KEY_3;
   public static final Icon KEY_4;
   public static final Icon KEY_5;
   public static final Icon KEY_6;
   public static final Icon KEY_7;
   public static final Icon KEY_8;
   public static final Icon KEY_9;
   public static final Icon KEY_0;
   public static final Icon KEY_MINUS;
   public static final Icon KEY_UNDERLINE;
   public static final Icon KEY_EQUALS;
   public static final Icon KEY_PLUS;
   public static final Icon KEY_BACKSPACE;
   public static final Icon KEY_TAB;
   public static final Icon KEY_Q;
   public static final Icon KEY_W;
   public static final Icon KEY_E;
   public static final Icon KEY_R;
   public static final Icon KEY_T;
   public static final Icon KEY_Y;
   public static final Icon KEY_U;
   public static final Icon KEY_I;
   public static final Icon KEY_O;
   public static final Icon KEY_P;
   public static final Icon KEY_LEFT_BRACKET;
   public static final Icon KEY_LEFT_BRACE;
   public static final Icon KEY_RIGHT_BRACKET;
   public static final Icon KEY_RIGHT_BRACE;
   public static final Icon KEY_CAPSLOCK;
   public static final Icon KEY_A;
   public static final Icon KEY_S;
   public static final Icon KEY_D;
   public static final Icon KEY_F;
   public static final Icon KEY_G;
   public static final Icon KEY_H;
   public static final Icon KEY_J;
   public static final Icon KEY_K;
   public static final Icon KEY_L;
   public static final Icon KEY_SEMICOLON;
   public static final Icon KEY_COLON;
   public static final Icon KEY_SINGLE_QUOTE;
   public static final Icon KEY_QUOTATION_MARK;
   public static final Icon KEY_UP_ARROW;
   public static final Icon KEY_SHIFT;
   public static final Icon KEY_Z;
   public static final Icon KEY_X;
   public static final Icon KEY_C;
   public static final Icon KEY_V;
   public static final Icon KEY_B;
   public static final Icon KEY_N;
   public static final Icon KEY_M;
   public static final Icon KEY_COMMA;
   public static final Icon KEY_LEFT_ANGLE_BRACKET;
   public static final Icon KEY_DOT;
   public static final Icon KEY_RIGHT_ANGLE_BRACKET;
   public static final Icon KEY_SLASH;
   public static final Icon KEY_QUESTION;
   public static final Icon KEY_DOWN_ARROW;
   public static final Icon KEY_CTRL;
   public static final Icon KEY_WINDOW;
   public static final Icon KEY_ALT;
   public static final Icon KEY_SPACE_SMALL;
   public static final Icon KEY_SPACE_MEDIUM;
   public static final Icon KEY_SPACE_LARGE;
   public static final Icon KEY_LEFT_ARROW;
   public static final Icon KEY_RIGHT_ARROW;
   public static final Icon KEY_FN;
   public static final Icon KEY_RIGHT_SHIFT;
   public static final Icon KEY_SCROLL_LOCK;
   public static final Icon KEY_PAUSE;
   public static final Icon KEY_DELETE;
   public static final Icon KEY_END;
   public static final Icon KEY_PAGE_UP;
   public static final Icon KEY_PAGE_DOWN;
   public static final Icon KEY_BACKSLASH;
   public static final Icon KEY_VERTICAL_SLASH;
   public static final Icon KEY_NUMLCOK;
   public static final Icon KEY_ENTER;
   public static final Icon KEY_ENTER_TWO;
   public static final Icon KEY_CAPSLOCK_TWO;
   public static final Icon KEY_TAB_TWO;
   public static final Icon SLIDER_TOGGLE;
   public static final Icon TLAUNCHER;
   public static final Icon ELY;

   public static void register() {
      IconRegistry.register("repl", REPL);
      IconRegistry.register("in", IN);
      IconRegistry.register("out", OUT);
      IconRegistry.register("html", HTML);
      IconRegistry.register("bullet", BULLET);
      IconRegistry.register("particle", PARTICLE);
      IconRegistry.register("scene", SCENE);
      IconRegistry.register("rewind", REWIND);
      IconRegistry.register("faces", FACES);
      IconRegistry.register("alex", ALEX);
      IconRegistry.register("selector", SELECTOR);
      IconRegistry.register("slash", SLASH);
      IconRegistry.register("text", TEXT);
      IconRegistry.register("like", LIKE);
      IconRegistry.register("dislike", DISLIKE);
      IconRegistry.register("youtube", YOUTUBE);
      IconRegistry.register("discord", DISCORD);
      IconRegistry.register("telegram", TELEGRAM);
      IconRegistry.register("vk", VK);
      IconRegistry.register("twitter", TWITTER);
      IconRegistry.register("solid_like", SOLID_LIKE);
      IconRegistry.register("solid_dislike", SOLID_DISLIKE);
      IconRegistry.register("hub", HUB);
      IconRegistry.register("github", GITHUB);
      IconRegistry.register("other_briefcase", OTHER_BRIEFCASE);
      IconRegistry.register("other_medkit", OTHER_MEDKIT);
      IconRegistry.register("other_wallet", OTHER_WALLET);
      IconRegistry.register("other_hanger", OTHER_HANGER);
      IconRegistry.register("other_stats", OTHER_STATS);
      IconRegistry.register("other_banner", OTHER_BANNER);
      IconRegistry.register("other_openedLock", OTHER_OPENED_LOCK);
      IconRegistry.register("other_closedLock", OTHER_CLOSED_LOCK);
      IconRegistry.register("other_flag", OTHER_FLAG);
      IconRegistry.register("other_finishFlag", OTHER_FINISHFLAG);
      IconRegistry.register("other_umbrella", OTHER_UMBRELLA);
      IconRegistry.register("other_star", OTHER_STAR);
      IconRegistry.register("other_star_2", OTHER_STAR_2);
      IconRegistry.register("other_dungeonKey", OTHER_DUNGEONKEY);
      IconRegistry.register("other_carKey", OTHER_CARKEY);
      IconRegistry.register("other_key", OTHER_KEY);
      IconRegistry.register("other_x", OTHER_X);
      IconRegistry.register("other_backpack", OTHER_BACKPACK);
      IconRegistry.register("other_glosary", OTHER_GLOSARY);
      IconRegistry.register("other_book", OTHER_BOOK);
      IconRegistry.register("other_document", OTHER_DOCUMENT);
      IconRegistry.register("other_candle", OTHER_CANDLE);
      IconRegistry.register("other_hook", OTHER_HOOK);
      IconRegistry.register("adminpanel_user", ADMINPANEL_USER);
      IconRegistry.register("adminpanel_user_white_cross", ADMINPANEL_USER_WHITE_CROSS);
      IconRegistry.register("adminpanel_user_red_cross", ADMINPANEL_USER_RED_CROSS);
      IconRegistry.register("adminpanel_user_message", ADMINPANEL_MESSAGE);
      IconRegistry.register("adminpanel_user_message_white_cross", ADMINPANEL_MESSAGE_WHITE_CROSS);
      IconRegistry.register("adminpanel_user_message_red_cross", ADMINPANEL_MESSAGE_RED_CROSS);
      IconRegistry.register("adminpanel_voice", ADMINPANEL_VOICE);
      IconRegistry.register("adminpanel_white_voice", ADMINPANEL_VOICE_WHITE_CROSS);
      IconRegistry.register("adminpanel_red_voice", ADMINPANEL_VOICE_RED_CROSS);
      IconRegistry.register("adminpanel_speaker", ADMINPANEL_SPEAKER);
      IconRegistry.register("adminpanel_speaker_white_cross", ADMINPANEL_SPEAKER_WHITE_CROSS);
      IconRegistry.register("adminpanel_speaker_red_cross", ADMINPANEL_SPEAKER_RED_CROSS);
      IconRegistry.register("adminpanel_speaker_muted", ADMINPANEL_SPEAKER_MUTED);
      IconRegistry.register("adminpanel_speaker_low", ADMINPANEL_SPEAKER_LOW);
      IconRegistry.register("adminpanel_speaker_high", ADMINPANEL_SPEAKER_HIGH);
      IconRegistry.register("tools_sword", TOOLS_SWORD);
      IconRegistry.register("tools_knife", TOOLS_KNIFE);
      IconRegistry.register("tools_dagger", TOOLS_DAGGER);
      IconRegistry.register("tools_shortSword", TOOLS_SHORTSWORD);
      IconRegistry.register("tools_katana", TOOLS_KATANA);
      IconRegistry.register("tools_hammer", TOOLS_HAMMER);
      IconRegistry.register("tools_screwdriver", TOOLS_SCREWDRIVER);
      IconRegistry.register("tools_shovel", TOOLS_SHOVEL);
      IconRegistry.register("tools_glove", TOOLS_GLOVE);
      IconRegistry.register("tools_shuriken", TOOLS_SHURIKEN);
      IconRegistry.register("tools_bow", TOOLS_BOW);
      IconRegistry.register("tools_longBow", TOOLS_LONGBOW);
      IconRegistry.register("tools_arrow", TOOLS_ARROW);
      IconRegistry.register("tools_flyingArrows", TOOLS_FLYINGARROWS);
      IconRegistry.register("tools_shot", TOOLS_SHOT);
      IconRegistry.register("tools_bullet", TOOLS_BULLET);
      IconRegistry.register("tools_pistol", TOOLS_PISTOL);
      IconRegistry.register("tools_glock", TOOLS_GLOCK);
      IconRegistry.register("tools_revolver", TOOLS_REVOLVER);
      IconRegistry.register("tools_uzi", TOOLS_UZI);
      IconRegistry.register("tools_dynamite", TOOLS_DYNAMITE);
      IconRegistry.register("tools_grenade", TOOLS_GRENADE);
      IconRegistry.register("tools_tnt", TOOLS_TNT);
      IconRegistry.register("clothes_crown", CLOTHES_CROWN);
      IconRegistry.register("clothes_minicrown", CLOTHES_MINICROWN);
      IconRegistry.register("clothes_cylinder", CLOTHES_CYLINDER);
      IconRegistry.register("clothes_hat", CLOTHES_HAT);
      IconRegistry.register("clothes_cap", CLOTHES_CAP);
      IconRegistry.register("clothes_christmasHat", CLOTHES_CHRISTMASHAT);
      IconRegistry.register("clothes_favour", CLOTHES_FAVOUR);
      IconRegistry.register("clothes_glasses", CLOTHES_GLASSES);
      IconRegistry.register("clothes_tShort", CLOTHES_TSHORT);
      IconRegistry.register("clothes_jacket", CLOTHES_JACKET);
      IconRegistry.register("clothes_pants", CLOTHES_PANTS);
      IconRegistry.register("clothes_boots", CLOTHES_BOOTS);
      IconRegistry.register("clothes_sneakers", CLOTHES_SNEAKERS);
      IconRegistry.register("clothes_moustache", CLOTHES_MOUSTACHE);
      IconRegistry.register("device_laptop", DEVICE_LAPTOP);
      IconRegistry.register("device_computer", DEVICE_COMPUTER);
      IconRegistry.register("device_computer_2", DEVICE_COMPUTER_2);
      IconRegistry.register("device_diskdrive", DEVICE_DISKDRIVE);
      IconRegistry.register("device_phone", DEVICE_PHONE);
      IconRegistry.register("device_radio", DEVICE_RADIO);
      IconRegistry.register("device_camera", DEVICE_CAMERA);
      IconRegistry.register("device_arcade", DEVICE_ARCADE);
      IconRegistry.register("device_antenna", DEVICE_ANTENNA);
      IconRegistry.register("device_clock", DEVICE_CLOCK);
      IconRegistry.register("device_mouse", DEVICE_MOUSE);
      IconRegistry.register("device_keyboard", DEVICE_KEYBOARD);
      IconRegistry.register("device_gamepad", DEVICE_GAMEPAD);
      IconRegistry.register("device_microphone", DEVICE_MICROPHONE);
      IconRegistry.register("device_headphones", DEVICE_HEADPHONES);
      IconRegistry.register("device_speaker", DEVICE_SPEAKER);
      IconRegistry.register("computer_light", COMPUTER_LIGHT);
      IconRegistry.register("computer_cursor", COMPUTER_CURSOR);
      IconRegistry.register("computer_click", COMPUTER_CLICK);
      IconRegistry.register("computer_shutdown", COMPUTER_SHUTDOWN);
      IconRegistry.register("computer_settings", COMPUTER_SETTINGS);
      IconRegistry.register("computer_usb", COMPUTER_USB);
      IconRegistry.register("computer_battery_4", COMPUTER_BATTERY_4);
      IconRegistry.register("computer_battery_3", COMPUTER_BATTERY_3);
      IconRegistry.register("computer_battery_2", COMPUTER_BATTERY_2);
      IconRegistry.register("computer_battery_1", COMPUTER_BATTERY_1);
      IconRegistry.register("computer_battery_charging", COMPUTER_CHARGING);
      IconRegistry.register("computer_notification", COMPUTER_NOTIFICATION);
      IconRegistry.register("computer_defender", COMPUTER_DEFENDER);
      IconRegistry.register("computer_home", COMPUTER_HOME);
      IconRegistry.register("computer_mail", COMPUTER_MAIL);
      IconRegistry.register("computer_market", COMPUTER_MARKET);
      IconRegistry.register("computer_map", COMPUTER_MAP);
      IconRegistry.register("computer_mapPoint", COMPUTER_MAPPOINT);
      IconRegistry.register("computer_share", COMPUTER_SHARE);
      IconRegistry.register("computer_share_2", COMPUTER_SHARE_2);
      IconRegistry.register("computer_folder", COMPUTER_FOLDER);
      IconRegistry.register("computer_file", COMPUTER_FILE);
      IconRegistry.register("computer_paste", COMPUTER_PASTE);
      IconRegistry.register("computer_creditCard", COMPUTER_CREDITCARD);
      IconRegistry.register("computer_piano", COMPUTER_PIANO);
      IconRegistry.register("computer_cd", COMPUTER_CD);
      IconRegistry.register("computer_cassete", COMPUTER_CASSETE);
      IconRegistry.register("computer_note", COMPUTER_NOTE);
      IconRegistry.register("computer_note_2", COMPUTER_NOTE_2);
      IconRegistry.register("paint_pencil", PAINT_PENCIL);
      IconRegistry.register("paint_pencilEraser", PAINT_PENCILERASER);
      IconRegistry.register("paint_highlithter", PAINT_HIGHLITGHTER);
      IconRegistry.register("paint_brush", PAINT_BRUSH);
      IconRegistry.register("paint_brush_2", PAINT_BRUSH_2);
      IconRegistry.register("paint_picker", PAINT_PICKER);
      IconRegistry.register("paint_eraser", PAINT_ERASER);
      IconRegistry.register("paint_pouring", PAINT_POURING);
      IconRegistry.register("paint_cut", PAINT_CUT);
      IconRegistry.register("food_pan", FOOD_PAN);
      IconRegistry.register("food_spoon", FOOD_SPOON);
      IconRegistry.register("food_meat", FOOD_MEAT);
      IconRegistry.register("food_pizza", FOOD_PIZZA);
      IconRegistry.register("food_bread", FOOD_BREAD);
      IconRegistry.register("food_soup", FOOD_SOUP);
      IconRegistry.register("food_cake", FOOD_CAKE);
      IconRegistry.register("food_chocolate", FOOD_CHOCOLATE);
      IconRegistry.register("food_iceCream", FOOD_ICECREAM);
      IconRegistry.register("food_iceCream_2", FOOD_ICECREAM_2);
      IconRegistry.register("food_chupaChups", FOOD_CHUPACHUPS);
      IconRegistry.register("food_lollipop", FOOD_LOLLIPOP);
      IconRegistry.register("food_christmasLollipop", FOOD_CHRISTMASLOLLIPOP);
      IconRegistry.register("food_tea", FOOD_TEA);
      IconRegistry.register("food_coffee", FOOD_COFFEE);
      IconRegistry.register("food_bear", FOOD_BEAR);
      IconRegistry.register("food_jam", FOOD_JAM);
      IconRegistry.register("food_champagne", FOOD_CHAMPAGNE);
      IconRegistry.register("food_cocaCola", FOOD_COCACOLA);
      IconRegistry.register("food_cup", FOOD_CUP);
      IconRegistry.register("food_glass", FOOD_GLASS);
      IconRegistry.register("food_vial", FOOD_VIAL);
      IconRegistry.register("food_potion", FOOD_POTION);
      IconRegistry.register("food_cigarette", FOOD_CIGARETTE);
      IconRegistry.register("food_pipe", FOOD_PIPE);
      IconRegistry.register("food_lighter", FOOD_LIGHTER);
      IconRegistry.register("food_hookah", FOOD_HOOKAH);
      IconRegistry.register("food_poop", FOOD_POOP);
      IconRegistry.register("emoji_smiley", EMOJI_SMILEY);
      IconRegistry.register("emoji_relaxed", EMOJI_RELAXED);
      IconRegistry.register("emoji_stuckOutTongue", EMOJI_STUCKOUTTONGUE);
      IconRegistry.register("emoji_smirking", EMOJI_SMIRKING);
      IconRegistry.register("emoji_cool", EMOJI_COOL);
      IconRegistry.register("emoji_sob", EMOJI_SOB);
      IconRegistry.register("emoji_verySob", EMOJI_VERYSOB);
      IconRegistry.register("emoji_confused", EMOJI_CONFUSED);
      IconRegistry.register("emoji_rage", EMOJI_RAGE);
      IconRegistry.register("emoji_skull_large", EMOJI_SKULL_LARGE);
      IconRegistry.register("emoji_skull_medium", EMOJI_SKULL_MEDIUM);
      IconRegistry.register("emoji_skull_small", EMOJI_SKULL_SMALL);
      IconRegistry.register("money_coin", MONEY_COIN);
      IconRegistry.register("money_coinDollar", MONEY_COINDOLLAR);
      IconRegistry.register("money_banknotes", MONEY_BANKNOTES);
      IconRegistry.register("money_bagMoney", MONEY_BAGMONEY);
      IconRegistry.register("key_escape", KEY_ESCAPE);
      IconRegistry.register("key_f1", KEY_F1);
      IconRegistry.register("key_f2", KEY_F2);
      IconRegistry.register("key_f3", KEY_F3);
      IconRegistry.register("key_f4", KEY_F4);
      IconRegistry.register("key_f5", KEY_F5);
      IconRegistry.register("key_f6", KEY_F6);
      IconRegistry.register("key_f7", KEY_F7);
      IconRegistry.register("key_f8", KEY_F8);
      IconRegistry.register("key_f9", KEY_F9);
      IconRegistry.register("key_f10", KEY_F10);
      IconRegistry.register("key_f11", KEY_F11);
      IconRegistry.register("key_f12", KEY_F12);
      IconRegistry.register("key_print", KEY_PRINT);
      IconRegistry.register("key_gravias", KEY_GRAVIAS);
      IconRegistry.register("key_tilda", KEY_TILDA);
      IconRegistry.register("key_exclamation", KEY_EXCLAMATION);
      IconRegistry.register("key_symbol", KEY_SYMBOL);
      IconRegistry.register("key_grid", KEY_GRID);
      IconRegistry.register("key_dollar", KEY_DOLLAR);
      IconRegistry.register("key_procent", KEY_PROCENT);
      IconRegistry.register("key_caret", KEY_CARET);
      IconRegistry.register("key_ampersand", KEY_AMPERSAND);
      IconRegistry.register("key_star", KEY_STAR);
      IconRegistry.register("key_left_parentthesis", KEY_LEFT_PARENTTHESIS);
      IconRegistry.register("key_right_parentthesis", KEY_RIGHT_PARENTTHESIS);
      IconRegistry.register("key_insert", KEY_INSERT);
      IconRegistry.register("key_home", KEY_HOME);
      IconRegistry.register("key_1", KEY_1);
      IconRegistry.register("key_2", KEY_2);
      IconRegistry.register("key_3", KEY_3);
      IconRegistry.register("key_4", KEY_4);
      IconRegistry.register("key_5", KEY_5);
      IconRegistry.register("key_6", KEY_6);
      IconRegistry.register("key_7", KEY_7);
      IconRegistry.register("key_8", KEY_8);
      IconRegistry.register("key_9", KEY_9);
      IconRegistry.register("key_0", KEY_0);
      IconRegistry.register("key_minus", KEY_MINUS);
      IconRegistry.register("key_underline", KEY_UNDERLINE);
      IconRegistry.register("key_equals", KEY_EQUALS);
      IconRegistry.register("key_plus", KEY_PLUS);
      IconRegistry.register("key_backspace", KEY_BACKSPACE);
      IconRegistry.register("key_tab", KEY_TAB);
      IconRegistry.register("key_q", KEY_Q);
      IconRegistry.register("key_w", KEY_W);
      IconRegistry.register("key_e", KEY_E);
      IconRegistry.register("key_r", KEY_R);
      IconRegistry.register("key_t", KEY_T);
      IconRegistry.register("key_y", KEY_Y);
      IconRegistry.register("key_u", KEY_U);
      IconRegistry.register("key_i", KEY_I);
      IconRegistry.register("key_o", KEY_O);
      IconRegistry.register("key_p", KEY_P);
      IconRegistry.register("key_left_bracket", KEY_LEFT_BRACKET);
      IconRegistry.register("key_right_bracket", KEY_RIGHT_BRACKET);
      IconRegistry.register("key_left_brace", KEY_LEFT_BRACE);
      IconRegistry.register("key_right_brace", KEY_RIGHT_BRACE);
      IconRegistry.register("key_capslock", KEY_CAPSLOCK);
      IconRegistry.register("key_A", KEY_A);
      IconRegistry.register("key_s", KEY_S);
      IconRegistry.register("key_d", KEY_D);
      IconRegistry.register("key_f", KEY_F);
      IconRegistry.register("key_g", KEY_G);
      IconRegistry.register("key_h", KEY_H);
      IconRegistry.register("key_j", KEY_J);
      IconRegistry.register("key_k", KEY_K);
      IconRegistry.register("key_l", KEY_L);
      IconRegistry.register("key_semilicolon", KEY_SEMICOLON);
      IconRegistry.register("key_colon", KEY_COLON);
      IconRegistry.register("key_single_quote", KEY_SINGLE_QUOTE);
      IconRegistry.register("key_quotation_mark", KEY_QUOTATION_MARK);
      IconRegistry.register("key_up_arrow", KEY_UP_ARROW);
      IconRegistry.register("key_shift", KEY_SHIFT);
      IconRegistry.register("key_z", KEY_Z);
      IconRegistry.register("key_x", KEY_X);
      IconRegistry.register("key_c", KEY_C);
      IconRegistry.register("key_v", KEY_V);
      IconRegistry.register("key_b", KEY_B);
      IconRegistry.register("key_n", KEY_N);
      IconRegistry.register("key_m", KEY_M);
      IconRegistry.register("key_comma", KEY_COMMA);
      IconRegistry.register("key_left_angle_bracket", KEY_LEFT_ANGLE_BRACKET);
      IconRegistry.register("key_dot", KEY_DOT);
      IconRegistry.register("key_right_angle_bracket", KEY_RIGHT_ANGLE_BRACKET);
      IconRegistry.register("key_slash", KEY_SLASH);
      IconRegistry.register("key_question", KEY_QUESTION);
      IconRegistry.register("key_down_arrow", KEY_DOWN_ARROW);
      IconRegistry.register("key_ctrl", KEY_CTRL);
      IconRegistry.register("key_window", KEY_WINDOW);
      IconRegistry.register("key_alt", KEY_ALT);
      IconRegistry.register("key_space_small", KEY_SPACE_SMALL);
      IconRegistry.register("key_space_medium", KEY_SPACE_MEDIUM);
      IconRegistry.register("key_space_large", KEY_SPACE_LARGE);
      IconRegistry.register("key_left_arrow", KEY_LEFT_ARROW);
      IconRegistry.register("key_right_arrow", KEY_RIGHT_ARROW);
      IconRegistry.register("key_fn", KEY_FN);
      IconRegistry.register("key_right_shift", KEY_RIGHT_SHIFT);
      IconRegistry.register("key_scroll_lock", KEY_SCROLL_LOCK);
      IconRegistry.register("key_pause", KEY_PAUSE);
      IconRegistry.register("key_delete", KEY_DELETE);
      IconRegistry.register("key_end", KEY_END);
      IconRegistry.register("key_page_up", KEY_PAGE_UP);
      IconRegistry.register("key_page_down", KEY_PAGE_DOWN);
      IconRegistry.register("key_backslash", KEY_BACKSLASH);
      IconRegistry.register("key_vertical_slash", KEY_VERTICAL_SLASH);
      IconRegistry.register("key_numlock", KEY_NUMLCOK);
      IconRegistry.register("key_enter", KEY_ENTER);
      IconRegistry.register("key_enter_two", KEY_ENTER_TWO);
      IconRegistry.register("key_capslock_two", KEY_CAPSLOCK_TWO);
      IconRegistry.register("key_tab_two", KEY_TAB_TWO);
      IconRegistry.register("slider_toggle", SLIDER_TOGGLE);
      IconRegistry.register("tlauncher", TLAUNCHER);
      IconRegistry.register("ely", ELY);
   }

   static {
      REPL = new Icon(TEXTURE, 0, 0);
      IN = new Icon(TEXTURE, 16, 0);
      OUT = new Icon(TEXTURE, 32, 0);
      HTML = new Icon(TEXTURE, 48, 0);
      BULLET = new Icon(LVICONS, 0, 224);
      PARTICLE = new Icon(LVICONS, 16, 224);
      SCENE = new Icon(LVICONS, 32, 224);
      REWIND = new Icon(LVICONS, 48, 224);
      FACES = new Icon(LVICONS, 64, 224);
      ALEX = new Icon(LVICONS, 80, 224);
      SELECTOR = new Icon(LVICONS, 96, 224);
      SLASH = new Icon(LVICONS, 112, 224);
      TEXT = new Icon(LVICONS, 128, 224);
      LIKE = new Icon(LVICONS, 144, 224);
      DISLIKE = new Icon(LVICONS, 160, 224);
      YOUTUBE = new Icon(LVICONS, 0, 240);
      DISCORD = new Icon(LVICONS, 16, 240);
      TELEGRAM = new Icon(LVICONS, 32, 240);
      VK = new Icon(LVICONS, 48, 240);
      TWITTER = new Icon(LVICONS, 64, 240);
      SOLID_LIKE = new Icon(LVICONS, 80, 240);
      SOLID_DISLIKE = new Icon(LVICONS, 96, 240);
      HUB = new Icon(LVICONS, 112, 240);
      GITHUB = new Icon(LVICONS, 128, 240);
      OTHER_BRIEFCASE = new Icon(LVICONS, 0, 0);
      OTHER_MEDKIT = new Icon(LVICONS, 16, 0);
      OTHER_WALLET = new Icon(LVICONS, 32, 0);
      OTHER_HANGER = new Icon(LVICONS, 48, 0);
      OTHER_STATS = new Icon(LVICONS, 64, 0);
      OTHER_BANNER = new Icon(LVICONS, 80, 0);
      OTHER_OPENED_LOCK = new Icon(LVICONS, 96, 0);
      OTHER_CLOSED_LOCK = new Icon(LVICONS, 112, 0);
      OTHER_FLAG = new Icon(LVICONS, 128, 0);
      OTHER_FINISHFLAG = new Icon(LVICONS, 144, 0);
      OTHER_UMBRELLA = new Icon(LVICONS, 160, 0);
      OTHER_STAR = new Icon(LVICONS, 176, 0);
      OTHER_STAR_2 = new Icon(LVICONS, 192, 0);
      OTHER_DUNGEONKEY = new Icon(LVICONS, 208, 0);
      OTHER_CARKEY = new Icon(LVICONS, 224, 0);
      OTHER_KEY = new Icon(LVICONS, 240, 0);
      OTHER_X = new Icon(LVICONS, 0, 16);
      OTHER_BACKPACK = new Icon(LVICONS, 16, 16);
      OTHER_GLOSARY = new Icon(LVICONS, 32, 16);
      OTHER_BOOK = new Icon(LVICONS, 48, 16);
      OTHER_DOCUMENT = new Icon(LVICONS, 64, 16);
      OTHER_CANDLE = new Icon(LVICONS, 80, 16);
      OTHER_HOOK = new Icon(LVICONS, 96, 16);
      ADMINPANEL_USER = new Icon(LVICONS, 0, 32);
      ADMINPANEL_USER_WHITE_CROSS = new Icon(LVICONS, 16, 32);
      ADMINPANEL_USER_RED_CROSS = new Icon(LVICONS, 32, 32);
      ADMINPANEL_MESSAGE = new Icon(LVICONS, 48, 32);
      ADMINPANEL_MESSAGE_WHITE_CROSS = new Icon(LVICONS, 64, 32);
      ADMINPANEL_MESSAGE_RED_CROSS = new Icon(LVICONS, 80, 32);
      ADMINPANEL_VOICE = new Icon(LVICONS, 96, 32);
      ADMINPANEL_VOICE_WHITE_CROSS = new Icon(LVICONS, 112, 32);
      ADMINPANEL_VOICE_RED_CROSS = new Icon(LVICONS, 128, 32);
      ADMINPANEL_SPEAKER = new Icon(LVICONS, 144, 32);
      ADMINPANEL_SPEAKER_WHITE_CROSS = new Icon(LVICONS, 160, 32);
      ADMINPANEL_SPEAKER_RED_CROSS = new Icon(LVICONS, 176, 32);
      ADMINPANEL_SPEAKER_MUTED = new Icon(LVICONS, 192, 32);
      ADMINPANEL_SPEAKER_LOW = new Icon(LVICONS, 208, 32);
      ADMINPANEL_SPEAKER_HIGH = new Icon(LVICONS, 224, 32);
      TOOLS_SWORD = new Icon(LVICONS, 0, 48);
      TOOLS_KNIFE = new Icon(LVICONS, 16, 48);
      TOOLS_DAGGER = new Icon(LVICONS, 32, 48);
      TOOLS_SHORTSWORD = new Icon(LVICONS, 48, 48);
      TOOLS_KATANA = new Icon(LVICONS, 64, 48);
      TOOLS_HAMMER = new Icon(LVICONS, 80, 48);
      TOOLS_SCREWDRIVER = new Icon(LVICONS, 96, 48);
      TOOLS_SHOVEL = new Icon(LVICONS, 112, 48);
      TOOLS_GLOVE = new Icon(LVICONS, 128, 48);
      TOOLS_SHURIKEN = new Icon(LVICONS, 144, 48);
      TOOLS_BOW = new Icon(LVICONS, 160, 48);
      TOOLS_LONGBOW = new Icon(LVICONS, 176, 48);
      TOOLS_ARROW = new Icon(LVICONS, 192, 48);
      TOOLS_FLYINGARROWS = new Icon(LVICONS, 208, 48);
      TOOLS_SHOT = new Icon(LVICONS, 224, 48);
      TOOLS_BULLET = new Icon(LVICONS, 240, 48);
      TOOLS_PISTOL = new Icon(LVICONS, 0, 64);
      TOOLS_GLOCK = new Icon(LVICONS, 16, 64);
      TOOLS_REVOLVER = new Icon(LVICONS, 32, 64);
      TOOLS_UZI = new Icon(LVICONS, 48, 64);
      TOOLS_DYNAMITE = new Icon(LVICONS, 64, 64);
      TOOLS_GRENADE = new Icon(LVICONS, 80, 64);
      TOOLS_TNT = new Icon(LVICONS, 96, 64);
      SLIDER_TOGGLE = new Icon(LVICONS, 113, 68, 13, 7);
      CLOTHES_CROWN = new Icon(LVICONS, 0, 80);
      CLOTHES_MINICROWN = new Icon(LVICONS, 16, 80);
      CLOTHES_CYLINDER = new Icon(LVICONS, 32, 80);
      CLOTHES_HAT = new Icon(LVICONS, 48, 80);
      CLOTHES_CAP = new Icon(LVICONS, 64, 80);
      CLOTHES_CHRISTMASHAT = new Icon(LVICONS, 80, 80);
      CLOTHES_FAVOUR = new Icon(LVICONS, 96, 80);
      CLOTHES_GLASSES = new Icon(LVICONS, 112, 80);
      CLOTHES_TSHORT = new Icon(LVICONS, 128, 80);
      CLOTHES_JACKET = new Icon(LVICONS, 144, 80);
      CLOTHES_PANTS = new Icon(LVICONS, 160, 80);
      CLOTHES_BOOTS = new Icon(LVICONS, 176, 80);
      CLOTHES_SNEAKERS = new Icon(LVICONS, 192, 80);
      CLOTHES_MOUSTACHE = new Icon(LVICONS, 208, 80);
      DEVICE_LAPTOP = new Icon(LVICONS, 0, 96);
      DEVICE_COMPUTER = new Icon(LVICONS, 16, 96);
      DEVICE_COMPUTER_2 = new Icon(LVICONS, 32, 96);
      DEVICE_DISKDRIVE = new Icon(LVICONS, 48, 96);
      DEVICE_PHONE = new Icon(LVICONS, 64, 96);
      DEVICE_RADIO = new Icon(LVICONS, 80, 96);
      DEVICE_CAMERA = new Icon(LVICONS, 96, 96);
      DEVICE_ARCADE = new Icon(LVICONS, 112, 96);
      DEVICE_ANTENNA = new Icon(LVICONS, 128, 96);
      DEVICE_CLOCK = new Icon(LVICONS, 144, 96);
      DEVICE_MOUSE = new Icon(LVICONS, 160, 96);
      DEVICE_KEYBOARD = new Icon(LVICONS, 176, 96);
      DEVICE_GAMEPAD = new Icon(LVICONS, 192, 96);
      DEVICE_MICROPHONE = new Icon(LVICONS, 208, 96);
      DEVICE_HEADPHONES = new Icon(LVICONS, 224, 96);
      DEVICE_SPEAKER = new Icon(LVICONS, 240, 96);
      COMPUTER_CURSOR = new Icon(LVICONS, 0, 112);
      COMPUTER_CLICK = new Icon(LVICONS, 16, 112);
      COMPUTER_SHUTDOWN = new Icon(LVICONS, 32, 112);
      COMPUTER_SETTINGS = new Icon(LVICONS, 48, 112);
      COMPUTER_USB = new Icon(LVICONS, 64, 112);
      COMPUTER_BATTERY_4 = new Icon(LVICONS, 80, 112);
      COMPUTER_BATTERY_3 = new Icon(LVICONS, 96, 112);
      COMPUTER_BATTERY_2 = new Icon(LVICONS, 112, 112);
      COMPUTER_BATTERY_1 = new Icon(LVICONS, 128, 112);
      COMPUTER_CHARGING = new Icon(LVICONS, 144, 112);
      COMPUTER_NOTIFICATION = new Icon(LVICONS, 160, 112);
      COMPUTER_DEFENDER = new Icon(LVICONS, 176, 112);
      COMPUTER_HOME = new Icon(LVICONS, 192, 112);
      COMPUTER_MAIL = new Icon(LVICONS, 208, 112);
      COMPUTER_MARKET = new Icon(LVICONS, 224, 112);
      COMPUTER_LIGHT = new Icon(LVICONS, 240, 112);
      COMPUTER_MAP = new Icon(LVICONS, 0, 128);
      COMPUTER_MAPPOINT = new Icon(LVICONS, 16, 128);
      COMPUTER_SHARE = new Icon(LVICONS, 32, 128);
      COMPUTER_SHARE_2 = new Icon(LVICONS, 48, 128);
      COMPUTER_FOLDER = new Icon(LVICONS, 64, 128);
      COMPUTER_FILE = new Icon(LVICONS, 80, 128);
      COMPUTER_PASTE = new Icon(LVICONS, 96, 128);
      COMPUTER_CREDITCARD = new Icon(LVICONS, 112, 128);
      COMPUTER_PIANO = new Icon(LVICONS, 128, 128);
      COMPUTER_CD = new Icon(LVICONS, 144, 128);
      COMPUTER_CASSETE = new Icon(LVICONS, 160, 128);
      COMPUTER_NOTE = new Icon(LVICONS, 176, 128);
      COMPUTER_NOTE_2 = new Icon(LVICONS, 192, 128);
      PAINT_PENCIL = new Icon(LVICONS, 0, 144);
      PAINT_PENCILERASER = new Icon(LVICONS, 16, 144);
      PAINT_HIGHLITGHTER = new Icon(LVICONS, 32, 144);
      PAINT_BRUSH = new Icon(LVICONS, 48, 144);
      PAINT_BRUSH_2 = new Icon(LVICONS, 64, 144);
      PAINT_PICKER = new Icon(LVICONS, 80, 144);
      PAINT_ERASER = new Icon(LVICONS, 96, 144);
      PAINT_POURING = new Icon(LVICONS, 112, 144);
      PAINT_CUT = new Icon(LVICONS, 128, 144);
      FOOD_PAN = new Icon(LVICONS, 0, 160);
      FOOD_SPOON = new Icon(LVICONS, 16, 160);
      FOOD_MEAT = new Icon(LVICONS, 32, 160);
      FOOD_PIZZA = new Icon(LVICONS, 48, 160);
      FOOD_BREAD = new Icon(LVICONS, 64, 160);
      FOOD_SOUP = new Icon(LVICONS, 80, 160);
      FOOD_CAKE = new Icon(LVICONS, 96, 160);
      FOOD_CHOCOLATE = new Icon(LVICONS, 112, 160);
      FOOD_ICECREAM = new Icon(LVICONS, 128, 160);
      FOOD_ICECREAM_2 = new Icon(LVICONS, 144, 160);
      FOOD_CHUPACHUPS = new Icon(LVICONS, 160, 160);
      FOOD_LOLLIPOP = new Icon(LVICONS, 176, 160);
      FOOD_CHRISTMASLOLLIPOP = new Icon(LVICONS, 192, 160);
      FOOD_TEA = new Icon(LVICONS, 208, 160);
      FOOD_COFFEE = new Icon(LVICONS, 224, 160);
      FOOD_BEAR = new Icon(LVICONS, 240, 160);
      FOOD_JAM = new Icon(LVICONS, 0, 176);
      FOOD_CHAMPAGNE = new Icon(LVICONS, 16, 176);
      FOOD_COCACOLA = new Icon(LVICONS, 32, 176);
      FOOD_CUP = new Icon(LVICONS, 48, 176);
      FOOD_GLASS = new Icon(LVICONS, 64, 176);
      FOOD_VIAL = new Icon(LVICONS, 80, 176);
      FOOD_POTION = new Icon(LVICONS, 96, 176);
      FOOD_CIGARETTE = new Icon(LVICONS, 112, 176);
      FOOD_PIPE = new Icon(LVICONS, 128, 176);
      FOOD_LIGHTER = new Icon(LVICONS, 144, 176);
      FOOD_HOOKAH = new Icon(LVICONS, 160, 176);
      FOOD_POOP = new Icon(LVICONS, 176, 176);
      EMOJI_SMILEY = new Icon(LVICONS, 0, 192);
      EMOJI_RELAXED = new Icon(LVICONS, 16, 192);
      EMOJI_STUCKOUTTONGUE = new Icon(LVICONS, 32, 192);
      EMOJI_SMIRKING = new Icon(LVICONS, 48, 192);
      EMOJI_COOL = new Icon(LVICONS, 64, 192);
      EMOJI_SOB = new Icon(LVICONS, 80, 192);
      EMOJI_VERYSOB = new Icon(LVICONS, 96, 192);
      EMOJI_CONFUSED = new Icon(LVICONS, 112, 192);
      EMOJI_RAGE = new Icon(LVICONS, 128, 192);
      EMOJI_SKULL_LARGE = new Icon(LVICONS, 144, 192);
      EMOJI_SKULL_MEDIUM = new Icon(LVICONS, 160, 192);
      EMOJI_SKULL_SMALL = new Icon(LVICONS, 176, 192);
      MONEY_COIN = new Icon(LVICONS, 0, 208);
      MONEY_COINDOLLAR = new Icon(LVICONS, 16, 208);
      MONEY_BANKNOTES = new Icon(LVICONS, 32, 208);
      MONEY_BAGMONEY = new Icon(LVICONS, 48, 208);
      KEY_ESCAPE = new Icon(KEYICONS, 0, 0, 32, 16);
      KEY_F1 = new Icon(KEYICONS, 32, 0);
      KEY_F2 = new Icon(KEYICONS, 48, 0);
      KEY_F3 = new Icon(KEYICONS, 64, 0);
      KEY_F4 = new Icon(KEYICONS, 80, 0);
      KEY_F5 = new Icon(KEYICONS, 96, 0);
      KEY_F6 = new Icon(KEYICONS, 112, 0);
      KEY_F7 = new Icon(KEYICONS, 128, 0);
      KEY_F8 = new Icon(KEYICONS, 144, 0);
      KEY_F9 = new Icon(KEYICONS, 160, 0);
      KEY_F10 = new Icon(KEYICONS, 176, 0);
      KEY_F11 = new Icon(KEYICONS, 192, 0);
      KEY_F12 = new Icon(KEYICONS, 208, 0);
      KEY_PRINT = new Icon(KEYICONS, 224, 0, 32, 16);
      KEY_GRAVIAS = new Icon(KEYICONS, 0, 16);
      KEY_TILDA = new Icon(KEYICONS, 16, 16);
      KEY_EXCLAMATION = new Icon(KEYICONS, 32, 16);
      KEY_SYMBOL = new Icon(KEYICONS, 48, 16);
      KEY_GRID = new Icon(KEYICONS, 64, 16);
      KEY_DOLLAR = new Icon(KEYICONS, 80, 16);
      KEY_PROCENT = new Icon(KEYICONS, 96, 16);
      KEY_CARET = new Icon(KEYICONS, 112, 16);
      KEY_AMPERSAND = new Icon(KEYICONS, 128, 16);
      KEY_STAR = new Icon(KEYICONS, 144, 16);
      KEY_LEFT_PARENTTHESIS = new Icon(KEYICONS, 160, 16);
      KEY_RIGHT_PARENTTHESIS = new Icon(KEYICONS, 176, 16);
      KEY_INSERT = new Icon(KEYICONS, 192, 16, 32, 16);
      KEY_HOME = new Icon(KEYICONS, 224, 16, 32, 16);
      KEY_1 = new Icon(KEYICONS, 0, 32);
      KEY_2 = new Icon(KEYICONS, 16, 32);
      KEY_3 = new Icon(KEYICONS, 32, 32);
      KEY_4 = new Icon(KEYICONS, 48, 32);
      KEY_5 = new Icon(KEYICONS, 64, 32);
      KEY_6 = new Icon(KEYICONS, 80, 32);
      KEY_7 = new Icon(KEYICONS, 96, 32);
      KEY_8 = new Icon(KEYICONS, 112, 32);
      KEY_9 = new Icon(KEYICONS, 128, 32);
      KEY_0 = new Icon(KEYICONS, 144, 32);
      KEY_MINUS = new Icon(KEYICONS, 160, 32);
      KEY_UNDERLINE = new Icon(KEYICONS, 176, 32);
      KEY_EQUALS = new Icon(KEYICONS, 192, 32);
      KEY_PLUS = new Icon(KEYICONS, 208, 32);
      KEY_BACKSPACE = new Icon(KEYICONS, 224, 32, 32, 16);
      KEY_TAB = new Icon(KEYICONS, 0, 48, 32, 16);
      KEY_Q = new Icon(KEYICONS, 32, 48);
      KEY_W = new Icon(KEYICONS, 48, 48);
      KEY_E = new Icon(KEYICONS, 64, 48);
      KEY_R = new Icon(KEYICONS, 80, 48);
      KEY_T = new Icon(KEYICONS, 96, 48);
      KEY_Y = new Icon(KEYICONS, 112, 48);
      KEY_U = new Icon(KEYICONS, 128, 48);
      KEY_I = new Icon(KEYICONS, 144, 48);
      KEY_O = new Icon(KEYICONS, 160, 48);
      KEY_P = new Icon(KEYICONS, 176, 48);
      KEY_LEFT_BRACKET = new Icon(KEYICONS, 192, 48);
      KEY_LEFT_BRACE = new Icon(KEYICONS, 208, 48);
      KEY_RIGHT_BRACKET = new Icon(KEYICONS, 224, 48);
      KEY_RIGHT_BRACE = new Icon(KEYICONS, 240, 48);
      KEY_CAPSLOCK = new Icon(KEYICONS, 0, 64, 32, 16);
      KEY_A = new Icon(KEYICONS, 32, 64);
      KEY_S = new Icon(KEYICONS, 48, 64);
      KEY_D = new Icon(KEYICONS, 64, 64);
      KEY_F = new Icon(KEYICONS, 80, 64);
      KEY_G = new Icon(KEYICONS, 96, 64);
      KEY_H = new Icon(KEYICONS, 112, 64);
      KEY_J = new Icon(KEYICONS, 128, 64);
      KEY_K = new Icon(KEYICONS, 144, 64);
      KEY_L = new Icon(KEYICONS, 160, 64);
      KEY_SEMICOLON = new Icon(KEYICONS, 176, 64);
      KEY_COLON = new Icon(KEYICONS, 192, 64);
      KEY_SINGLE_QUOTE = new Icon(KEYICONS, 208, 64);
      KEY_QUOTATION_MARK = new Icon(KEYICONS, 224, 64);
      KEY_UP_ARROW = new Icon(KEYICONS, 240, 64);
      KEY_SHIFT = new Icon(KEYICONS, 0, 80, 32, 16);
      KEY_Z = new Icon(KEYICONS, 32, 80);
      KEY_X = new Icon(KEYICONS, 48, 80);
      KEY_C = new Icon(KEYICONS, 64, 80);
      KEY_V = new Icon(KEYICONS, 80, 80);
      KEY_B = new Icon(KEYICONS, 96, 80);
      KEY_N = new Icon(KEYICONS, 112, 80);
      KEY_M = new Icon(KEYICONS, 128, 80);
      KEY_COMMA = new Icon(KEYICONS, 144, 80);
      KEY_LEFT_ANGLE_BRACKET = new Icon(KEYICONS, 160, 80);
      KEY_DOT = new Icon(KEYICONS, 176, 80);
      KEY_RIGHT_ANGLE_BRACKET = new Icon(KEYICONS, 192, 80);
      KEY_SLASH = new Icon(KEYICONS, 208, 80);
      KEY_QUESTION = new Icon(KEYICONS, 224, 80);
      KEY_DOWN_ARROW = new Icon(KEYICONS, 240, 80);
      KEY_CTRL = new Icon(KEYICONS, 0, 96, 32, 16);
      KEY_WINDOW = new Icon(KEYICONS, 32, 96);
      KEY_ALT = new Icon(KEYICONS, 48, 96, 32, 16);
      KEY_SPACE_SMALL = new Icon(KEYICONS, 80, 96);
      KEY_SPACE_MEDIUM = new Icon(KEYICONS, 96, 96, 32, 16);
      KEY_SPACE_LARGE = new Icon(KEYICONS, 128, 96, 64, 16);
      KEY_LEFT_ARROW = new Icon(KEYICONS, 192, 96);
      KEY_RIGHT_ARROW = new Icon(KEYICONS, 192, 208);
      KEY_FN = new Icon(KEYICONS, 208, 96);
      KEY_RIGHT_SHIFT = new Icon(KEYICONS, 224, 96, 32, 16);
      KEY_SCROLL_LOCK = new Icon(KEYICONS, 192, 112, 32, 16);
      KEY_PAUSE = new Icon(KEYICONS, 224, 112, 32, 16);
      KEY_DELETE = new Icon(KEYICONS, 192, 128, 32, 16);
      KEY_END = new Icon(KEYICONS, 224, 128, 32, 16);
      KEY_PAGE_UP = new Icon(KEYICONS, 192, 144, 32, 16);
      KEY_PAGE_DOWN = new Icon(KEYICONS, 224, 144, 32, 16);
      KEY_BACKSLASH = new Icon(KEYICONS, 192, 160);
      KEY_VERTICAL_SLASH = new Icon(KEYICONS, 208, 160);
      KEY_NUMLCOK = new Icon(KEYICONS, 224, 160, 32, 16);
      KEY_ENTER = new Icon(KEYICONS, 192, 176, 32, 16);
      KEY_ENTER_TWO = new Icon(KEYICONS, 224, 176, 32, 16);
      KEY_CAPSLOCK_TWO = new Icon(KEYICONS, 192, 192, 32, 16);
      KEY_TAB_TWO = new Icon(KEYICONS, 224, 192, 32, 16);
      TLAUNCHER = new Icon(LVICONS, 127, 64, 13, 12);
      ELY = new Icon(LVICONS, 140, 64, 13, 12);
   }
}